FROM node:latest

WORKDIR /app
COPY ./package.json /app

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install
RUN npm install react-scripts@3.0.1 -g
COPY . /app/

EXPOSE 3000
EXPOSE 9229
CMD ["npm", "run", "debug"]
